siderolabs/theila

frontend/package-lock.json, frontend/package.json, frontend/src/api/client.ts, frontend/src/main.ts
Using infinite exponential retry backoff.
Recreate watches when connection is restored.
Also switch back to `console.log` for logs. As `typescript-logging`
isn't really better.
=> feat: make JS websocket reconnect on connection loss

.babelrc, .eslintrc.yaml, .jestrc, frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/api/client.ts, frontend/src/components/ShellMenuItem.vue, frontend/src/components/StackedList.vue, frontend/src/components/TBreadcrumbs.vue, frontend/src/router/index.ts, frontend/src/views/Clusters.vue, frontend/src/views/Nodes.vue, frontend/src/views/Pods.vue, frontend/src/views/Servers.vue, frontend/src/views/SidebarCluster.vue, frontend/src/views/SidebarRoot.vue, internal/backend/server_test.go, internal/frontend/frontend.go
Also fixed the bug with stopped watches being re-subscribed on
socker reconnect.
=> feat: implement breadcrumbs component, add support for table header

frontend/src/api/watch.ts, frontend/src/components/StackedList.vue, frontend/src/components/TAlert.vue
And use it in the `StackedList` to display errors and no records info.
=> feat: implement notifications component

.babelrc, .dockerignore, .jestrc, Dockerfile, Makefile, cmd/theila/main.go, frontend/src/components/TDropdown.vue, internal/frontend/frontend.go
=> fix: cobra command was initialized but not actually used

.babelrc, .codecov.yml, .conform.yaml, .dockerignore, .drone.yml, .jestrc, .kres.yaml, CHANGELOG.md, Dockerfile, Makefile, hack/release.sh, hack/release.toml, internal/frontend/frontend.go
This is the official v0.1.0-alpha.0 release.
=> release(v0.1.0-alpha.0): prepare release

frontend/src/components/StackedList.vue, frontend/src/components/Watch.vue, frontend/src/views/Clusters.vue, frontend/src/views/Servers.vue, frontend/src/views/cluster/Nodes.vue, frontend/src/views/cluster/Pods.vue, frontend/src/views/node/Services.vue
This will allow displaying a generic list of items, not only watchable
lists.
=> refactor: separate Watch from StackedList

frontend/src/components/TChart.vue
Previously spinner placement was completely incorrect.
=> fix: display error message and use proper layout for the spinner

frontend/src/components/ServerListItem.vue, frontend/src/components/StackedList.vue, frontend/src/views/Servers.vue
Just rewamped the UI of that page to be in sync with the wireframes we
have.
Also implemented expand/collapse for each item in the row to show more
details.
=> feat: align Sidero servers list outlook with the wireframes

frontend/src/components/TModal.vue, frontend/src/components/TStat.vue, frontend/src/components/Watch.vue, frontend/src/views/Servers.vue
Show the total amount of servers, allocated and capacity.
=> feat: implement stats component and add stats to the servers page

frontend/src/views/SidebarNode.vue, frontend/src/views/node/Logs.vue
Add ability to get Dmesg logs in the UI.
Also optimize log viewer a bit, by accumulating frequent updates
in the buffer.
Otherwise Vue reactive updates are killing the browser.
=> feat: dmesg logs page

CHANGELOG.md, README.md, hack/release.toml
This is the official v0.1.0-alpha.1 release.
=> release(v0.1.0-alpha.1): prepare release

frontend/src/components/ServerListItem.vue, frontend/src/views/SidebarRoot.vue
Fixes: https://github.com/talos-systems/theila/issues/56
=> fix: server labels key/value order and chevron orientation

frontend/src/components/ClusterListItem.vue
Adds an "Upgrade Kubernetes" to the context menu for a cluster list
item.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
=> feat: add upgrade UI for CAPI clusters

CHANGELOG.md, hack/release.toml
This is the official v0.1.0-alpha.2 release.
=> release(v0.1.0-alpha.2): prepare release

frontend/src/views/node/Overview.vue
Make it resemble `talosctl dashboard` more.
=> feat: add top processes list to the Overview page

CHANGELOG.md, hack/release.toml
This is the official v0.1.0-beta.0 release.
=> release(v0.1.0-beta.0): prepare release

frontend/src/views/node/Logs.vue, frontend/src/views/node/Overview.vue
Changed padding on the Overview page and the behavior of logs
view to show empty box if there's no logs.
=> feat: small UI adjustments

frontend/src/components/TChart.vue, frontend/src/views/node/Overview.vue
Otherwise it looks weird if you zoom out.
=> fix: make charts height resize depending on the screen height

frontend/package-lock.json, frontend/src/api/resources.ts, frontend/src/context.ts, frontend/src/views/Clusters.vue, frontend/src/views/Servers.vue, frontend/src/views/SidebarNode.vue, frontend/src/views/cluster/Nodes.vue, frontend/src/views/cluster/Pods.vue, frontend/src/views/node/Monitor.vue, frontend/src/views/node/Overview.vue
This is crucial if the code base grows in the future.
If we update resource versions or change names in Talos it will be
easier to update them everywhere.
=> chore: define constants for all used resource types

docs/context.md
Document how to properly compose the context parameters for different
kinds of requests on the client.
=> docs: describe client context types, usage

frontend/src/views/Servers/components/TServersContentListItem.vue
Display the extendend hardware information that was added via https://github.com/siderolabs/sidero/pull/735 in the Theila UI
Signed-off-by: Gerard de Leeuw <gdeleeuw@leeuwit.nl>
=> feat: show the extended hardware info
