cmd/theila/main.go
frontend/src/components/Preview.vue
go.mod
internal/backend/logging/logging.go
internal/backend/server.go
internal/backend/ws/session.go
internal/backend/ws/subscription.go
internal/backend/ws/ws.go

This actually simplifies adding the context to the logs.
Using `Sugar()` only wherever we `fmt.Sprintf` something.

feat: use plain zap instead of SugaredLogger everywhere

---

frontend/src/App.vue
frontend/src/components/Shell.vue
frontend/src/components/ShellMenuItem.vue
frontend/src/components/TModal.vue
frontend/src/router/index.ts
frontend/src/theme.ts
frontend/src/views/Settings.vue
frontend/src/views/SidebarRoot.vue
frontend/tailwind.config.js

Introduced a generic primitives for viewing modal windows.
Also reused shell component in settings view.
This PR helped to learn more about Vue 3 composition API primitives like
`ref` and `watch`.

feat: implement appearance settings modal window

---

frontend/src/api/client.ts
frontend/src/api/watch.ts
frontend/src/components/ClusterListItem.vue
frontend/src/components/StackedList.vue
frontend/src/views/Clusters.vue
frontend/src/views/Servers.vue
frontend/src/views/cluster/Nodes.vue
frontend/src/views/cluster/Pods.vue
frontend/src/views/node/Services.vue
go.mod
go.sum
internal/backend/runtime/kubernetes/kubernetes.go

Fixes: https://github.com/talos-systems/theila/issues/16
Now watch object maintains the item list by itself, which is at the same
time is reactive and can be used in any UI elements.
Also introduced sort methods with default being by namespace and id.
And fixed item lookup to consider not only resource name but also
namespace.

feat: decouple watch list from the view

---

frontend/src/theme.ts
frontend/src/views/SidebarRoot.vue

Looks pretty much the same as before, but now the header can be clicked
to collapse the section.
No animations yet. It looks like PITA with Tailwind flex-col and gap.
It works kinda, but is glitchy.

feat: make root sidebar sections collapsible

---

frontend/src/components/ServerListItem.vue
frontend/src/components/StackedList.vue
frontend/src/components/TInput.vue
frontend/src/components/Watch.vue
frontend/src/views/Clusters.vue
frontend/src/views/Servers.vue
frontend/src/views/cluster/Nodes.vue
frontend/src/views/cluster/Pods.vue
frontend/src/views/node/Services.vue

Enabled searching by name for any of the resources we display.
Additionally search servers by labels and cpu version.

feat: make stacked lists searchable

---

frontend/src/components/StackedList.vue
frontend/src/components/Watch.vue

Talos items do not have `metadata.name`, so use watch `id` method
instead. That method automatically picks the right id for the item
depending on the source.

fix: resolve services search issues

---

frontend/src/App.vue

Otherwise router may enter some weird state when it tries to show
`Clusters` for the cluster without CAPI and so on.

fix: navigate home when changing the context

---

cmd/theila/main.go
frontend/src/components/StackedList.vue
frontend/src/components/TDropdown.vue
frontend/src/components/Watch.vue
frontend/src/views/Servers.vue
internal/backend/grpc/grpc.go
internal/backend/server_test.go

Added that function to the `Watch` and `StackedList` so it can be
actually used in any other lists we have.
+ Address tests flakiness by using different ports for the gRPC proxy.

feat: allow filtering servers by picking from predefined categories

---

frontend/src/api/watch.ts
frontend/src/components/Watch.vue
internal/backend/server_test.go

Mysteries of JS `this` scope strike again (Multiplied by Vue).
That was breaking search and somehow was not noticeable without it.

fix: resolve the issue with idFn value generating undefined ids

---

frontend/src/api/watch.ts
frontend/src/components/StackedList.vue
frontend/src/components/Watch.vue
frontend/src/views/Servers.vue

Sort options are configurable by the input rules, so it's easy to add
that on the other pages as soon as we decide on what options we want to
have there.

feat: add ability to pick sort order on the servers page

---

frontend/src/components/TChart.vue
frontend/src/views/node/Services.vue

Now as each Talos resource has created and updated timestamp, it is
possible to properly display event timestamp on the graph.

feat: use updated timestamp to display event time on the graph

---

frontend/src/api/grpc.ts
frontend/src/components/NodeListItem.vue
frontend/src/components/ServerListItem.vue
frontend/src/components/ShellMenuItem.vue
frontend/src/components/StackedList.vue
frontend/src/components/TButton.vue
frontend/src/components/TDropdown.vue
frontend/src/components/TLabel.vue
frontend/src/components/TModal.vue
frontend/src/components/TNotification.vue
frontend/src/context.ts
frontend/src/modal.ts
frontend/src/router/index.ts
frontend/src/views/Reboot.vue
frontend/src/views/Settings.vue
frontend/src/views/cluster/Nodes.vue
frontend/src/views/node/Logs.vue
frontend/tailwind.config.js

Add that functional to the `Nodes` page.
Now there's a dropdown menu that has reboot option, which opens the
modal dialog to confirm the reboot.
If it fails to issue reboot command we show failure notification popup.
Additionally add readiness status to each node on the nodes page.

feat: implement node reboot controls

---

frontend/public/index.html
frontend/src/components/TChart.vue

Fixes: https://github.com/talos-systems/theila/issues/55
During the initial load it gets all points as a separate updates.
Accumulate them into a single one to stop Vue from overloading the
renderer.

fix: accumulate chart updates into a single update

---

frontend/src/api/grpc.ts
frontend/src/api/watch.ts
frontend/src/components/ClusterListItem.vue
frontend/src/components/NodeListItem.vue
frontend/src/context.ts
frontend/src/router/index.ts
frontend/src/views/Upgrade.vue
frontend/src/views/cluster/Nodes.vue
frontend/src/views/cluster/Pods.vue
frontend/src/views/node/Overview.vue
frontend/src/views/node/Services.vue
internal/backend/runtime/talos/talos.go

Fixes: https://github.com/talos-systems/theila/issues/53
Also fix CAPI upgrade related issues:
- cluster name wasn't passed to the context.
- workaround for the issue of context name being different for `Talos` and
`Kubernetes` runtimes. Do not extract cluster name from the context,
just strip `admin@` on the backend in the `Talos` runtime.
- query parameter `name` -> `cluster`.

fix: node IP not being truncated

---

frontend/src/components/LogView.vue
frontend/src/components/NodeListItem.vue
frontend/src/components/TCheckbox.vue
frontend/src/router/index.ts
frontend/src/views/Reset.vue

Add a new context menu item that opens node reset dialog.
Add a new modal window with reset options, which provides a way to
toggle graceful, reboot flags.

feat: implement node Reset

---

frontend/src/api/grpc.ts
frontend/src/api/resources.ts
frontend/src/components/ClusterListItem.vue
frontend/src/components/NodeListItem.vue
frontend/src/components/TModal.vue
frontend/src/context.ts
frontend/src/views/Reboot.vue
frontend/src/views/Reset.vue
frontend/src/views/SidebarNode.vue
frontend/src/views/SidebarRoot.vue
frontend/src/views/Upgrade.vue
frontend/src/views/node/Logs.vue
frontend/src/views/node/Services.vue

Fixes: https://github.com/talos-systems/theila/issues/65
Get rid of `getCluster` and replace it with `getContext` everywhere.
Also introduce global types registry to encode outgoing objects in
`Create` and `Update` gRPC calls.
And convert `camelCase` format to `snake_case` to avoid having the mix of them in the request.

refactor: use the same object for gRPC metadata context and messages

---

frontend/src/api/client.ts

This should help when the container runs behind some https ingress.

fix: use secure websockets if the page itself is using https

---

frontend/src/views/node/Overview.vue

`hostname` is not always equals to the actual `nodename`.
Luckily we conveniently have `nodename` resource already defined.

fix: read node name from nodename resource instead of hostname

---

internal/backend/runtime/theila/controllers/upgrade.go
internal/backend/server.go
internal/backend/ws/ws.go

Default implementation does not consider `x-forwarded-host` header which
breaks `wss` tunnels in some cases.
Besides that, get rid of all `self-hosted` checks, as it doesn't work on newer Talos versions as there is no bootstrap status anymore.

fix: properly handle Same-Origin header in websockets

---

frontend/src/router/index.ts
frontend/src/views/SidebarRoot.vue
internal/backend/grpc/resource.go
internal/backend/runtime/kubernetes/kubernetes.go

Also fix breadcrumbs errors on default context.

fix: talosconfig/kubeconfig when using the default context

---

frontend/src/api/client.ts

fix: reset reconnect timeouts after the client is reconnected

---

frontend/src/App.vue
frontend/src/api/client.ts
frontend/src/api/watch.ts

Slower connection and websocket proxy exposed more problems on the
client side reconnect logic:
- closing connection does not abort any pending watch requests so they
time out and incorrectly mark watch as failed.
Also got rid of annoying `subscription does not exist` errors after
reconnect when the server is restarted.
There should be no need to clean up subscriptions if the client has lost
the connection completely as the server should delete the session and
all linked subscriptions.
Found yet another issue with default context usage: was picking default
talos context as well, what is incorrect as per current implementation
Kubernetes context should always be the leading one. Otherwise you may
get your Theila app in the weird state when you set `kubectl config
use-context A` and …

fix: more websocket client bugfixes

---

frontend/src/components/ClusterListItem.vue

Format was changed, but this wasn't updated in this particular
component.

fix: properly pass label selector to the metadata in ClusterListItem

---

.babelrc
.conform.yaml
.gitignore
.jestrc
internal/frontend/frontend.go

This folder is now created by `dev-server` command, so it should be
added to `.gitignore`.

fix: add `frontend/node_modules` to gitignore

---

internal/backend/runtime/theila/controllers/upgrade.go

Namespace should be the name of the cluster, not `default`.

fix: properly set TaskStatus namespace in the initial call

---

go.mod
go.sum

Older `capi-utils` was using an incorrect name for the secret.

fix: update capi-utils to fix talosconfig requests for CAPI clusters

---

frontend/src/methods/index.ts
frontend/src/views/Overview/components/TOverviewContent.vue

It was showing capacity instead of used.

fix: invert chart value for cpu, storage and memory on the overview page

---

frontend/src/components/common/MenuItem/TMenuItem.vue
frontend/src/components/views/SideBar/components/TSideBarList.vue
frontend/src/methods/index.ts
frontend/src/views/Overview/Overview.vue
frontend/src/views/Overview/components/TOverviewContent.vue
frontend/src/views/Overview/components/TOverviewNodesUsage.vue

Also, remove unnecessary complexity from the Overview page which was
pulled from the charts component.
Keep track only of the last point and don't support several series. Also
limit the amount of points we request to the minumum value.

fix: properly update servers menu item when the context is changed

---

frontend/src/views/Nodes/components/TNodesMonitorChart.vue
frontend/src/views/node/Monitor.vue

Previously it was using percent values, but was showing it as GIB and
Cores.

fix: use proper units for memory and CPU charts on the node monitor page

---

frontend/src/App.vue
frontend/src/context.ts
frontend/src/views/Kubernetes/TKubernetesContent.vue
frontend/src/views/Servers/components/TServersContent.vue

Before `getAllocated` was returning just the count of servers, use
filter to count the amount of the servers `inUse`.
Also fix wording on the Kubernetes Upgrades page, when the list is
empty.

fix: properly calculate servers capacity

---

internal/backend/runtime/kubernetes/kubernetes.go

RLock was used in the write operation.

fix: get rid of racy code in the kubeconfig request code

---

README.md
frontend/src/components/TAlert.vue

restyle TAlert component
Signed-off-by: evgeniybryzh<evgeniy@merge.rocks>

feat: TAlert

---

frontend/src/components/THeader/THeader.vue

Removed error notification from THeader component.
Signed-off-by: evgeniybryzh<evgeniy@merge.rocks>

fix: remove t-header error notification

---

frontend/src/views/Nodes/components/TNodesOverviewContent.vue
frontend/src/views/Pods/components/TPodsList.vue

Fixed Pods page's age format and also fixed container runtime version alignment.
Signed-off-by: evgeniybryzh<evgeniy@merge.rocks>

fix: display delta time for pod's age
